### ISSUE TITLE
pushing back the notebook fails

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#226]
committing and pushing a jupyter notebook fails:

```
    HTTPServerRequest(protocol='http', host='jupyterhub.renga.build', method='PUT', uri='/user/rok/fbf4a14acba321e8a4bc5e13d9aba203/git/commit', version='HTTP/1.1', remote_ip='172.19.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab_commit_push.py", line 77, in put
        branch = self.get_current_user()['name'] + '-' + env_slug
    TypeError: must be str, not NoneType
[E 2018-05-17 22:46:54.777 SingleUserNotebookApp log:150] {
      "X-Xsrftoken": "2|e1aa578d|956cf79fdbae302f60fb4c2fcb02444f|1526596887",
      "X-Requested-With": "XMLHttpRequest",
      "X-Real-Ip": "172.19.0.1",
      "X-Forwarded-Server": "8e53c18a0dfb",
      "X-Forwarded-Proto": "http,http",
      "X-Forwarded-Port": "80,80",
      "X-Forwarded-Host": "jupyterhub.renga.build",
      "X-Forwarded-For": "172.19.0.1,::ffff:172.19.0.9",
      "Referer": "http://jupyterhub.renga.build/user/rok/fbf4a14acba321e8a4bc5e13d9aba203//notebooks/notebooks/Analysis.ipynb",
      "Origin": "http://jupyterhub.renga.build",
      "Dnt": "1",
      "Cookie": "user-rok-fbf4a14acba321e8a4bc5e13d9aba203=2|1:0|10:1526596887|41:user-rok-fbf4a14acba321e8a4bc5e13d9aba203|48:YWUwYWQ4Y2MtNDM3MC00OTZjLWFlM2QtYzVkN2MwYzQyZDg3|e4cdc4d3735c8f98d08cee1abf8d2becba5581d3a20654631293378a206b3c6f; service-projects-oauth-state=eyJuZXh0X3VybCI6ICIvc2VydmljZXMvcHJvamVjdHMvcm9rL3dlYXRoZXItemgvYjBlMjhmNTgyM2VmZDg1NzMxODMxNmEzM2QyNTM2MDk1Y2MzYTVmNC9ub3RlYm9va3MvQW5hbHlzaXMuaXB5bmIiLCAidXVpZCI6ICI1OWI1OGE1YmRkYmU0ODkxYjZmNjM3YWI0YWRlYmFkZSJ9; service-projects=31b2418d-be09-45d5-a1fb-1eef9400ab5b; _xsrf=2|e1aa578d|956cf79fdbae302f60fb4c2fcb02444f|1526596887",
      "Content-Type": "application/json",
      "Accept-Language": "en-US,en;q=0.9,sl;q=0.8,fr;q=0.7",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Content-Length": "68",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36",
      "Host": "jupyterhub.renga.build",
      "Connection": "close"
    }
```

need to change the custom branch name.

**Comment by rokroskar** [comment]
closed by #227
