### ISSUE TITLE
committing back the notebook fails on k8s

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku#261]
Using the gitlab commit/push button on testing.datascience.ch results in:

![image](https://user-images.githubusercontent.com/3353586/40942101-559f9634-684d-11e8-83b7-ae0f1c906c61.png)

and 

```
[E 2018-06-04 21:00:02.681 SingleUserNotebookApp web:1621] Uncaught exception PUT /jupyterhub/user/rok.roskar/rok-2erosk-first-2dst-21c928b/git/commit (10.39.0.0)
    HTTPServerRequest(protocol='https', host='testing.datascience.ch', method='PUT', uri='/jupyterhub/user/rok.roskar/rok-2erosk-first-2dst-21c928b/git/commit', version='HTTP/1.1', remote_ip='10.39.0.0')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
        return f(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/mixins.py", line 50, in get
        server_data = self.gitlab.http_get(path, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/__init__.py", line 753, in http_get
        streamed=streamed, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/__init__.py", line 731, in http_request
        response_body=result.content)
    gitlab.exceptions.GitlabHttpError: 404: 404 Project Not Found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/gitlab_commit_push.py", line 72, in put
        gl_project = gl.projects.get('{0}/{1}'.format(namespace, project))
      File "/opt/conda/lib/python3.6/site-packages/gitlab/exceptions.py", line 253, in wrapped_f
        raise error(e.error_message, e.response_code, e.response_body)
    gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab_commit_push.py", line 75, in put
        raise web.HTTPError(401, 'Not authorized to view project.')
    NameError: name 'web' is not defined
```

**Comment by leafty** [comment]
Got something a bit different:
```
[E 2018-06-14 06:53:57.525 SingleUserNotebookApp web:1621] Uncaught exception PUT /jupyterhub/user/leafty/leafty-weather-2d-cff50f3/git/commit (10.39.0.0)
    HTTPServerRequest(protocol='https', host='testing.datascience.ch', method='PUT', uri='/jupyterhub/user/leafty/leafty-weather-2d-cff50f3/git/commit', version='HTTP/1.1', remote_ip='10.39.0.0')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
        return f(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/mixins.py", line 50, in get
        server_data = self.gitlab.http_get(path, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/__init__.py", line 753, in http_get
        streamed=streamed, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/__init__.py", line 731, in http_request
        response_body=result.content)
    gitlab.exceptions.GitlabHttpError: 404: 404 Branch Not Found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/gitlab_commit_push.py", line 79, in put
        gl_branch = gl_project.branches.get(branch)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/exceptions.py", line 253, in wrapped_f
        raise error(e.error_message, e.response_code, e.response_body)
    gitlab.exceptions.GitlabGetError: 404: 404 Branch Not Found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/gitlab/exceptions.py", line 251, in wrapped_f
        return f(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/mixins.py", line 225, in create
        server_data = self.gitlab.http_post(path, post_data=data, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/__init__.py", line 825, in http_post
        post_data=post_data, files=files, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab/__init__.py", line 731, in http_request
        response_body=result.content)
    gitlab.exceptions.GitlabHttpError: 403: 403 Forbidden

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/gitlab_commit_push.py", line 83, in put
        'ref': ref,
      File "/opt/conda/lib/python3.6/site-packages/gitlab/exceptions.py", line 253, in wrapped_f
        raise error(e.error_message, e.response_code, e.response_body)
    gitlab.exceptions.GitlabCreateError: 403: 403 Forbidden
```
