### ISSUE TITLE
renku session start fails with 404 Client Error: Not Found for url: http+docker://localhost

### ISSUE THREAD

**Issue by rawlik** [SwissDataScienceCenter/renku#2847]
**Describe the bug**
`renku session start` fails and tells me I found a bug

**Link to project**
https://renkulab.io/gitlab/stamplab/phase-contrast-beats-attenuation-for-breast-ct

**To Reproduce**
1. Create an Ubuntu 22.04 VM on google cloud compute engine
1. [Install docker](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04)
2. Install pip and renku
3. login to renkulab.io
4. run renku clone
5. try starting a session

**Expected behavior**
A session to start

**Screenshots and/or execution output**
```
michal_rawlik@kalgan:~/phase-contrast-beats-attenuation-for-breast-ct$ renku session start
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: print
## Describe the bug
A clear and concise description.

## Details
*Please verify and redact the details.*

**Renku version:** 1.10.0
**OS:** Linux (#32-Ubuntu SMP Wed Nov 23 21:46:01 UTC 2022)
**Python:** 3.10.6


### Traceback

Traceback (most recent call last):
  File "[...]/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "[...]/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/registry.renkulab.io/stamplab/phase-contrast-beats-attenuation-for-breast-ct:88a8fc6/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/renku/core/session/docker.py", line 81, in find_image
    self.docker_client().images.get(image_name)
  File "[...]/docker/models/images.py", line 314, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "[...]/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "[...]/docker/api/image.py", line 251, in inspect_image
    return self._result(
  File "[...]/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "[...]/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "[...]/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/registry.renkulab.io/stamplab/phase-contrast-beats-attenuation-for-breast-ct:88a8fc6/json: Not Found ("no such image: registry.renkulab.io/stamplab/phase-contrast-beats-attenuation-for-breast-ct:88a8fc6: No such image: registry.renkulab.io/stamplab/phase-contrast-beats-attenuation-for-breast-ct:88a8fc6")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "[...]/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/images/create?tag=88a8fc6&fromImage=registry.renkulab.io%2Fstamplab%2Fphase-contrast-beats-attenuation-for-breast-ct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/session.py", line 222, in start
    session_start_command()
  File "[...]/renku/command/command_builder/command.py", line 252, in execute
    output = self._operation(*args, **kwargs)  # type: ignore
  File "[...]/renku/core/session/session.py", line 88, in session_start
    if not provider_api.find_image(image_name, config):
  File "[...]/renku/core/session/docker.py", line 85, in find_image
    self.docker_client().images.pull(image_name)
  File "[...]/docker/models/images.py", line 444, in pull
    pull_log = self.client.api.pull(
  File "[...]/docker/api/image.py", line 428, in pull
    self._raise_for_status(response)
  File "[...]/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "[...]/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=88a8fc6&fromImage=registry.renkulab.io%2Fstamplab%2Fphase-contrast-beats-attenuation-for-breast-ct: Internal Server Error ("Head "https://registry.renkulab.io/v2/stamplab/phase-contrast-beats-attenuation-for-breast-ct/manifests/88a8fc6": denied: access forbidden")
```

**Run environment (please complete the following information):**
 - local terminal
 - Jupyterlab 
 - renku 1.10
 - python 3.10.6
 - no browser

**Comment by sphamba** [comment]
I have the same problem when trying to start a renku session on WSL from a cloned freshly made project (renku 1.10.0). It does not matter whether I clone it using ssh or https.

Switching the visibility of the project from private to public makes the issue disappear.
