### ISSUE TITLE
minikube: make minikube-deploy fails

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku#305]
While followed the steps in [minikube.rst](https://github.com/SwissDataScienceCenter/renku/blob/master/docs/developer/minikube.rst), all goes fine until it starts renku when running the ```make minikube-deploy``` command:

```
Release "renku" does not exist. Installing it now.
Error: timed out waiting for the condition
Traceback (most recent call last):
  File "scripts/minikube_deploy.py", line 186, in <module>
    main()
  File "scripts/minikube_deploy.py", line 90, in main
    run(helm_deploy_cmd).check_returncode()
  File "/Users/???/miniconda3/lib/python3.6/subprocess.py", line 369, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['helm', 'upgrade', 'renku', '/var/folders/fj/h70409hj3hjc2wvhj9893b9w0000gn/T/tmpuqj_g02g/renku-0.1.0-fa9a8bb.tgz', '--install', '--namespace', 'renku', '-f', '../renku/charts/minikube-values.yaml', '--set', 'global.renku.domain=192.168.64.2', '--set', 'ui.gitlabUrl=http://192.168.64.2/gitlab', '--set', 'ui.jupyterhubUrl=http://192.168.64.2/jupyterhub', '--set', 'jupyterhub.hub.extraEnv.GITLAB_URL=http://192.168.64.2/gitlab', '--set', 'gitlab.registry.externalUrl=http://192.168.64.2:30105/']' returned non-zero exit status 1.
make: *** [minikube-deploy] Error 1
```

Running the same command again gives a different error:

```
Running: helm upgrade renku /var/folders/fj/h70409hj3hjc2wvhj9893b9w0000gn/T/tmp01t19kr8/renku-0.0-unclean-28a278f.tgz --install --namespace renku -f ../renku/charts/minikube-values.yaml --set global.renku.domain=192.168.64.2 --set ui.gitlabUrl=http://192.168.64.2/gitlab --set ui.jupyterhubUrl=http://192.168.64.2/jupyterhub --set jupyterhub.hub.extraEnv.GITLAB_URL=http://192.168.64.2/gitlab --set gitlab.registry.externalUrl=http://192.168.64.2:30105/
Error: UPGRADE FAILED: "renku" has no deployed releases
Traceback (most recent call last):
  File "scripts/minikube_deploy.py", line 186, in <module>
    main()
  File "scripts/minikube_deploy.py", line 90, in main
    run(helm_deploy_cmd).check_returncode()
  File "/Users/???/miniconda3/lib/python3.6/subprocess.py", line 369, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['helm', 'upgrade', 'renku', '/var/folders/fj/h70409hj3hjc2wvhj9893b9w0000gn/T/tmp01t19kr8/renku-0.0-unclean-28a278f.tgz', '--install', '--namespace', 'renku', '-f', '../renku/charts/minikube-values.yaml', '--set', 'global.renku.domain=192.168.64.2', '--set', 'ui.gitlabUrl=http://192.168.64.2/gitlab', '--set', 'ui.jupyterhubUrl=http://192.168.64.2/jupyterhub', '--set', 'jupyterhub.hub.extraEnv.GITLAB_URL=http://192.168.64.2/gitlab', '--set', 'gitlab.registry.externalUrl=http://192.168.64.2:30105/']' returned non-zero exit status 1.
make: *** [minikube-deploy] Error 1
```

**Comment by leafty** [comment]
Will increase the timeout threshold and include docs in case of failed helm upgrade.
