### ISSUE TITLE
minikube-deploy fails with: RuntimeError: Could not register runner 

### ISSUE THREAD

**Issue by flinz** [SwissDataScienceCenter/renku#409]
Trying to deploy by `make minikube-deploy` on OSX 10.13.4.

1) I got an error 
```
Error: no repository definition for https://swissdatasciencecenter.github.io/helm-charts/. Please add them via 'helm repo add'
```
which could be fixed by running (analogous to the documentation)
```
helm repo add renku https://swissdatasciencecenter.github.io/helm-charts
```

2) I now get a error after deploy, stopping the actual application
```bash
Traceback (most recent call last):
  File "scripts/minikube_deploy.py", line 255, in <module>
    main()
  File "scripts/minikube_deploy.py", line 105, in main
    deploy_runner()
  File "scripts/minikube_deploy.py", line 251, in deploy_runner
    raise RuntimeError('Could not register runner:\n{}'.format(register_runner.stdout.decode('utf-8')))
RuntimeError: Could not register runner:
Running in system-mode.

ERROR: Registering runner... failed                 runner=8dbf016f status=couldn't execute POST against http://192.168.99.100/gitlab/api/v4/runners: Post http://192.168.99.100/gitlab/api/v4/runners: dial tcp 192.168.99.100:80: getsockopt: connection refused
PANIC: Failed to register this runner. Perhaps you are having network problems

make: *** [minikube-deploy] Error 1
```
[Full log is here ](https://github.com/SwissDataScienceCenter/renku/files/2347906/renkulog.txt)

**Comment by leafty** [comment]
Did you run
```
helm upgrade --install nginx-ingress --namespace kube-system \
    --set controller.hostNetwork=true \
    stable/nginx-ingress
```
before
```
make minikube-deploy
```
?

It looks like the runner container cannot access the ingress pod.

As you can see from the logs, it tries to run:
```
docker exec -ti gitlab-runner gitlab-runner register \
    -n -u http://192.168.99.100/gitlab/ --name docker-minikube \
    -r 8dbf016f5b73d5608390183bbea9ce5fbed83a9dadefa719245ab93eb255cc29 \
    --executor docker --locked=false --run-untagged=true \
    --docker-image="docker:stable" --docker-privileged \
    --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
    --tag-list image-build --docker-pull-policy if-not-present
```

**Comment by flinz** [comment]
I thought I did, but probably forgot to run it after some intermediate steps.
This fixed the issue, thanks!
