### ISSUE TITLE
Invalid path when exporting dataset to Zenodo

### ISSUE THREAD

**Issue by jen-thomas** [SwissDataScienceCenter/renku#614]
I added data to an existing dataset:
`jen@jen:~/projects/ace_data_management/renku-projects/meteorology/data$ renku dataset add meteorology /home/jen/projects/ace_data_management/data_to_archive_post_cruise/met_data/raw/data_file_header.txt`

then exported it to Zenodo: 

`jen@jen:~/projects/ace_data_management/renku-projects/meteorology/data$ renku dataset export meteorology zenodo`

After adding the access token, it seems that an invalid path to the files being exported, was used: 

` '/home/jen/projects/ace_data_management/renku-projects/meteorology/data/data/meteorology/README.txt'`

Please see below for the bug report: 

jen@jen:~/projects/ace_data_management/renku-projects/meteorology/data$ renku dataset export meteorology zenodo
Before exporting, you must configure an access token
Create one at: https://zenodo.org/account/settings/applications/tokens/new/
Access token: ###
  0%|                                                                                                                                   | 0/2 [00:00<?, ?it/s]
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: print
## Describe the bug
A clear and concise description.

## Details
*Please verify and redact the details.*

**Renku version:** 0.5.2
**OS:** Linux (#1 SMP Debian 4.9.144-3.1 (2019-02-19))
**Python:** 3.7.3

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/cli/_client.py", line 83, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/cli/dataset.py", line 495, in export_
    destination = exporter.export(publish)
  File "[...]/site-packages/renku/cli/_providers/zenodo.py", line 446, in export
    deposition.upload_file(file_.full_path, )
  File "[...]/site-packages/renku/cli/_providers/zenodo.py", line 349, in upload_file
    file = {'file': open(str(filepath), 'rb')}
FileNotFoundError: [Errno 2] No such file or directory: '/home/jen/projects/ace_data_management/renku-projects/meteorology/data/data/meteorology/README.txt'
```
Please let me know if you need any more information.

**Comment by ciyer** [comment]
Hi there! Just wanted to let you know that much of the team (including those who can investigate this issue) are currently on vacation, but someone will take a look at it and get back to you soon.
